title = "TOML CONF"
[server]
    ip = "http://192.168.0.104:8080"
    port = 3000
[desk]
    #游戏状态时间：0.等待玩家加入1.游戏开始倒计时2.发牌3.每个玩家操作时间4.结算时间5.结束动画6.游戏终止动画
    GameStateTime = [0,20,9,30,20,10,6]

    DeskFullplayerNum   = 2  #桌子的满玩家数量
    DeskMinplayerNum    = 2  #开始游戏的最小人数
    Desk1RoundLosePoint = 20 #第一轮弃牌输的点数
    Desk2RoundLosePoint = 40 #第二轮弃牌输的点数
    DeskMaxLosePoint    = 80 #最多输80点
    #测试一定要是13张
    FirstPlayerCards = [1,2,3,4,5,6,7,8,9,10,11,12,13]
    WildCard = 0

[redis]
    redisAddr      = "192.168.0.104:6379"
    redisPassword  = ""
    redisDB        = 1

#数据库
[db]
    host     = "192.168.0.104"
    post     = 3306
    dbName   = "user-center"
    userName = "user-center"
    password = "user-center"
    network  = "tcp"